services:
  backend:
    build:
      context: ./Service
    ports:
      - "8080:8080"
    env_file:
      - ./Service/.env

  frontend:
    build:
      context: ./Quick-Gen/client
      args:
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
        VITE_BASE_URL: /api

    ports:
      - "80:80"

    depends_on:
      - backend